language: python
python:
  - "3.3"
  - "3.4"
  - "nightly"

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python3-gi gir1.2-gtk-3.0

# command to install dependencies
install: 
  - python3 setup.py develop
# command to run tests
script:
  - cd tests && python3 -m unittest -bv