language: python
python:
  - "3.3"
  - "3.4"
  - "nightly"

sudo: false
addons:
  apt:
    packages:
      - libglib2.0-dev
      - libgtk-3-dev
      - libffi-dev

# command to install dependencies
install: 
  - export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
  # Install PyGObject
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/3.2/pygobject-3.2.2.tar.xz -O pygobject.tar.xz
  - tar xf pygobject.tar.xz
  - cd pygobject-3.2.2
  - ./configure --prefix=$VIRT_ROOT
  - make
  - make install
  - cd ..

  # Other PyPI dependencies
  - python3 setup.py develop
# command to run tests
script:
  - cd tests && python3 -m unittest -bv