language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

sudo: false
addons:
  apt:
    packages:
      - libglib2.0-dev
      - libgtk-3-dev
      - libffi-dev
      - python3-dev
      - gobject-introspection

env:
  global:
    - GOBJECT_VERDIR=3.2
    - GOBJECT_VERSION=3.2.2

# command to install dependencies
install: 
  # These have to happen after the venv is activated
  - export PKG_CONFIG_PATH=$VIRTUAL_ENV/lib/pkgconfig
  # Here's hoping there's only one
  - export PYTHON_INCLUDES=-I$(echo $VIRTUAL_ENV/include/*)

  # Debug
  - env | sort
  - ls -l $VIRTUAL_ENV/include/*
  - ls -l /opt/python/3.4.2/include/python3.4m

  # Install PyGObject
  - wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/$GOBJECT_VERDIR/pygobject-$GOBJECT_VERSION.tar.xz
  - tar xf pygobject-$GOBJECT_VERSION.tar.xz
  - cd pygobject-$GOBJECT_VERSION
  - ./configure --prefix=$VIRTUAL_ENV
  - make
  - make install
  - cd ..

  # Other PyPI dependencies
  - python setup.py develop
# command to run tests
script:
  - cd tests && python -m unittest -bv